// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v5.26.1
// source: proto/hello.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "hello";

export interface HelloReq {
  msg: string;
}

export interface HelloRes {
  msg: string;
}

function createBaseHelloReq(): HelloReq {
  return { msg: "" };
}

export const HelloReq: MessageFns<HelloReq> = {
  encode(message: HelloReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== "") {
      writer.uint32(10).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloReq {
    return { msg: isSet(object.msg) ? globalThis.String(object.msg) : "" };
  },

  toJSON(message: HelloReq): unknown {
    const obj: any = {};
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloReq>, I>>(base?: I): HelloReq {
    return HelloReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloReq>, I>>(object: I): HelloReq {
    const message = createBaseHelloReq();
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseHelloRes(): HelloRes {
  return { msg: "" };
}

export const HelloRes: MessageFns<HelloRes> = {
  encode(message: HelloRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== "") {
      writer.uint32(10).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloRes {
    return { msg: isSet(object.msg) ? globalThis.String(object.msg) : "" };
  },

  toJSON(message: HelloRes): unknown {
    const obj: any = {};
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloRes>, I>>(base?: I): HelloRes {
    return HelloRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloRes>, I>>(object: I): HelloRes {
    const message = createBaseHelloRes();
    message.msg = object.msg ?? "";
    return message;
  },
};

/** Hello is a test service */
export type HelloService = typeof HelloService;
export const HelloService = {
  /** Hello rpc is a test rpc */
  hello: {
    path: "/hello.Hello/Hello",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HelloReq): Buffer => Buffer.from(HelloReq.encode(value).finish()),
    requestDeserialize: (value: Buffer): HelloReq => HelloReq.decode(value),
    responseSerialize: (value: HelloRes): Buffer => Buffer.from(HelloRes.encode(value).finish()),
    responseDeserialize: (value: Buffer): HelloRes => HelloRes.decode(value),
  },
} as const;

export interface HelloServer extends UntypedServiceImplementation {
  /** Hello rpc is a test rpc */
  hello: handleUnaryCall<HelloReq, HelloRes>;
}

export interface HelloClient extends Client {
  /** Hello rpc is a test rpc */
  hello(request: HelloReq, callback: (error: ServiceError | null, response: HelloRes) => void): ClientUnaryCall;
  hello(
    request: HelloReq,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HelloRes) => void,
  ): ClientUnaryCall;
  hello(
    request: HelloReq,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HelloRes) => void,
  ): ClientUnaryCall;
}

export const HelloClient = makeGenericClientConstructor(HelloService, "hello.Hello") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): HelloClient;
  service: typeof HelloService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
